
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.3-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $BIGQUERY_SERVICE_ACCOUNT_JSON > ${HOME}/bigquery-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install dbt
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Postgres"
          environment:
            POSTGRES_TEST_HOST: localhost
            POSTGRES_TEST_USER: root
            POSTGRES_TEST_PASS: ''
            POSTGRES_TEST_PORT: 5432
            POSTGRES_TEST_DBNAME: circle_test
          command: |
            . venv/bin/activate
            cd integration_tests
            dbt deps --target postgres
            dbt seed --target postgres --full-refresh
            dbt run --target postgres --full-refresh --vars 'update: false'
            dbt run --target postgres --vars 'update: true'
            dbt test --target postgres

      - run:
          name: "Run Tests - Redshift"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target redshift
            dbt seed --target redshift --full-refresh
            dbt run --target redshift --full-refresh --vars 'update: false'
            dbt run --target redshift --vars 'update: true'
            dbt test --target redshift

      - run:
          name: "Run Tests - Snowflake"
          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target snowflake
            dbt seed --target snowflake --full-refresh
            dbt run --target snowflake --full-refresh --vars 'update: false'
            dbt run --target snowflake --vars 'update: true'
            dbt test --target snowflake

      - run:
          name: "Run Tests - BigQuery"
          environment:
              BIGQUERY_SERVICE_KEY_PATH: "/home/circleci/bigquery-service-key.json"

          command: |
            . venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps --target bigquery
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery --full-refresh --vars 'update: false'
            dbt run --target bigquery --vars 'update: true'
            dbt test --target bigquery

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
