version: 2

models:
  - name: snowplow_base_events
    description: '{{ doc("snowplow_base_events") }}'

    columns:      
        - name: app_id
          description: Application ID
          tests: 
              - not_null
          
        - name: platform
          description: Platform
              
        - name: etl_tstamp
          description: Timestamp event began ETL
              
        - name: collector_tstamp
          description: Time stamp for the event recorded by the collector
              
        - name: dvce_created_tstamp
          description: Timestamp event was recorded on the client device
              
        - name: event
          description: The type of event recorded
              
        - name: event_id
          description: A UUID for each event
          tests:
              - not_null
              
        - name: txn_id
          description: Transaction ID set client-side, used to de-dupe records
              
        - name: name_tracker
          description: Tracker namespace
              
        - name: v_tracker
          description: Tracker version
              
        - name: v_collector
          description: Collector version
              
        - name: v_etl
          description: ETL version
              
        - name: user_id
          description: Unique ID set by business
              
        - name: user_ipaddress
          description: User IP address
              
        - name: user_fingerprint
          description: A user fingerprint generated by looking at the individual browser features
              
        - name: domain_userid
          description: User ID set by Snowplow using 1st party cookie
              
        - name: domain_sessionidx
          description: A visit / session index
              
        - name: network_userid
          description: User ID set by Snowplow using 3rd party cookie
              
        - name: geo_country
          description: ISO 3166-1 code for the country the visitor is located in
              
        - name: geo_region
          description: ISO-3166-2 code for country region the visitor is in
              
        - name: geo_city
          description: City the visitor is in
              
        - name: geo_zipcode
          description: Postcode the visitor is in
              
        - name: geo_latitude
          description: Visitor location latitude
              
        - name: geo_longitude
          description: Visitor location longitude
              
        - name: geo_region_name
          description: Visitor region name
              
        - name: ip_isp
          description: Visitor's ISP
              
        - name: ip_organization
          description: Organization associated with the visitor's IP address - defaults to ISP name if none is found
              
        - name: ip_domain
          description: Second level domain name associated with the visitor's IP address
              
        - name: ip_netspeed
          description: Visitor's connection type
              
        - name: page_url
          description: The page URL
              
        - name: page_title
          description: Web page title
              
        - name: page_referrer
          description: URL of the referrer
              
        - name: page_urlscheme
          description: Scheme aka protocol
              
        - name: page_urlhost
          description: Host aka domain
              
        - name: page_urlport
          description: Port if specified, 80 if not
              
        - name: page_urlpath
          description: Path to page
              
        - name: page_urlquery
          description: Querystring
              
        - name: page_urlfragment
          description: Fragment aka anchor
              
        - name: refr_urlscheme
          description: Referer scheme
              
        - name: refr_urlhost
          description: Referer host
              
        - name: refr_urlport
          description: Referer port
              
        - name: refr_urlpath
          description: Referer page path
              
        - name: refr_urlquery
          description: Referer URL querystring
              
        - name: refr_urlfragment
          description: Referer URL fragment
              
        - name: refr_medium
          description: Type of referer
              
        - name: refr_source
          description: Name of referer if recognised
              
        - name: refr_term
          description: Keywords if source is a search engine
              
        - name: mkt_medium
          description: Type of traffic source
              
        - name: mkt_source
          description: The company / website where the traffic came from
              
        - name: mkt_term
          description: Any keywords associated with the referrer
              
        - name: mkt_content
          description: The content of the ad. (Or an ID so that it can be looked up.)

        - name: mkt_campaign
          description: The campaign ID
              
        - name: contexts
          description: Contexts attached to event by Tracker
              
        - name: se_category
          description: Category of event
              
        - name: se_action
          description: Action performed / event name
              
        - name: se_label
          description: The object of the action e.g. the ID of the video played or SKU of the product added-to-basket
              
        - name: se_property
          description: A property associated with the object of the action
              
        - name: se_value
          description: A value associated with the event / action e.g. the value of goods added-to-basket
              
        - name: tr_orderid
          description: Order ID
              
        - name: tr_affiliation
          description: Transaction affiliation (e.g. store where sale took place)
              
        - name: tr_total
          description: Total transaction value
              
        - name: tr_tax
          description: Total tax included in transaction value
              
        - name: tr_shipping
          description: Delivery cost charged
              
        - name: tr_city
          description: Delivery address, city
              
        - name: tr_state
          description: Delivery address, state
              
        - name: tr_country
          description: Delivery address, country
              
        - name: ti_orderid
          description: Order ID
              
        - name: ti_sku
          description: Product SKU
              
        - name: ti_name
          description: Product name
              
        - name: ti_category
          description: Product category
              
        - name: ti_price
          description: Product unit price
              
        - name: ti_quantity
          description: Number of product in transaction
              
        - name: pp_xoffset_min
          description: Minimum page x offset seen in the last ping period
              
        - name: pp_xoffset_max
          description: Maximum page x offset seen in the last ping period
              
        - name: pp_yoffset_min
          description: Minimum page y offset seen in the last ping period
              
        - name: pp_yoffset_max
          description: Maximum page y offset seen in the last ping period
              
        - name: useragent
          description: Raw useragent
              
        - name: br_name
          description: Browser name
              
        - name: br_family
          description: Browser family
              
        - name: br_version
          description: Browser version
              
        - name: br_type
          description: Browser type
              
        - name: br_renderengine
          description: Browser rendering engine
              
        - name: br_lang
          description: Language the browser is set to
              
        - name: br_features_pdf
          description: Whether the browser recognizes PDFs
              
        - name: br_features_flash
          description: Whether Flash is installed
              
        - name: br_features_java
          description: Whether Java is installed
              
        - name: br_features_director
          description: Whether Adobe Shockwave is installed
              
        - name: br_features_quicktime
          description: Whether QuickTime is installed
              
        - name: br_features_realplayer
          description: Whether RealPlayer is installed
              
        - name: br_features_windowsmedia
          description: Whether mplayer2 is installed
              
        - name: br_features_gears
          description: Whether Google Gears is installed
              
        - name: br_features_silverlight
          description: Whether Microsoft Silverlight is installed
              
        - name: br_cookies
          description: Whether cookies are enabled
              
        - name: br_colordepth
          description: Bit depth of the browser color palette
              
        - name: br_viewwidth
          description: Viewport width
              
        - name: br_viewheight
          description: Viewport height
              
        - name: os_name
          description: Name of operating system
              
        - name: os_family
          description: Operating system family
              
        - name: os_manufacturer
          description: Company responsible for OS
              
        - name: os_timezone
          description: Client operating system timezone
              
        - name: dvce_type
          description: Type of device
              
        - name: dvce_ismobile
          description: Is the device mobile?
              
        - name: dvce_screenwidth
          description: Screen width in pixels
              
        - name: dvce_screenheight
          description: Screen height in pixels
              
        - name: doc_charset
          description: The page’s character encoding
              
        - name: doc_width
          description: The page's width in pixels
              
        - name: doc_height
          description: The page's height in pixels
              
        - name: tr_currency
          description: Currency
              
        - name: tr_total_base
          description: Total in base currency
              
        - name: tr_tax_base
          description: Total tax in base currency
              
        - name: tr_shipping_base
          description: Delivery cost in base currency
              
        - name: ti_currency
          description: Currency
              
        - name: ti_price_base
          description: Price in base currency
              
        - name: base_currency
          description: Reporting currency
              
        - name: geo_timezone
          description: Visitor timezone name
              
        - name: mkt_clickid
          description: The click ID
              
        - name: mkt_network
          description: The ad network to which the click ID belongs
              
        - name: etl_tags
          description: JSON of tags for this ETL run
              
        - name: dvce_sent_tstamp
          description: When the event was sent by the client device
              
        - name: refr_domain_userid
          description: The Snowplow domain_userid of the referring website
              
        - name: refr_dvce_tstamp
          description: The time of attaching the domain_userid to the inbound link
              
        - name: domain_sessionid
          description: A visit / session identifier
              
        - name: derived_tstamp
          description: Timestamp making allowance for innaccurate device clock
              
        - name: event_vendor
          description: Who defined the event
              
        - name: event_name
          description: Event name
              
        - name: event_format
          description: Format for event
              
        - name: event_version
          description: Version of event schema
              
        - name: event_fingerprint
          description: Hash client-set event fields
              
        - name: true_tstamp
          description: User-set "true timestamp" for the event
              
        - name: _piped_at
