
version: 2

models:
    - name: snowplow_sessions
      description: '{{ doc("snowplow_sessions") }}'
      
      columns:
          - name: session_id
            description: A visit / session identifier
            tests:
                - not_null
                - unique
                    
          - name: user_custom_id
            description: Unique ID set by business, user_id
                    
          - name: inferred_user_id
                    
          - name: exit_page_url
            description: The last page URL
                
          - name: session_cookie_index
             
          - name: user_snowplow_domain_id
            description: User ID set by Snowplow using 1st party cookie
             
          - name: user_snowplow_crossdomain_id
            description: User ID set by Snowplow using 3rd party cookie
             
          - name: session_index
            description: A visit / session index
             
          - name: session_start
            description: Timestamp for the start of the session on your preferred clock
             
          - name: session_end
            description: Timestamp for the end of the session on your preferred clock
             
          - name: session_start_local
            description: Timestamp for the start of the session on the user's clock
             
          - name: session_end_local
            description: Timestamp for the end of the session on the user's clock
             
          - name: page_views
            description: Number of page views within this session
             
          - name: time_engaged_in_s
            description: Time spent by the user on this visit
             
          - name: time_engaged_in_s_tier
            description: Range of time spent by the user on this visit
             
          - name: user_bounced
            description: Did the user bounce on their first page view in this session?
             
          - name: first_page_url
            description: The page URL
             
          - name: first_page_url_scheme
            description: Scheme aka protocol
             
          - name: first_page_url_host
            description: Host aka domain
             
          - name: first_page_url_port
            description: Port if specified, 80 if not
             
          - name: first_page_url_path
            description: Path to page
             
          - name: first_page_url_query
            description: Querystring
             
          - name: first_page_url_fragment
            description: Fragment aka anchor
             
          - name: first_page_title
            description: Web page title
             
          - name: referer_url
            description: The referer URL
             
          - name: referer_url_scheme
            description: Referer scheme
             
          - name: referer_url_host
            description: Referer host
             
          - name: referer_url_port
            description: Referer port
             
          - name: referer_url_path
            description: Referer page path
             
          - name: referer_url_query
            description: Referer URL querystring
             
          - name: referer_url_fragment
            description: Referer URL fragment
             
          - name: referer_medium
            description: Type of referer
             
          - name: referer_source
            description: Name of referer if recognised
             
          - name: referer_term
            description: Keywords if source is a search engine
            
          - name: marketing_medium
            description: Type of traffic source
            
          - name: marketing_source
            description: The company / website where the traffic came from
            
          - name: marketing_term
            description: Any keywords associated with the referer
            
          - name: marketing_content
            description: The content of the ad. (Or an ID so that it can be looked up.)
            
          - name: marketing_campaign
            description: The campaign ID
            
          - name: marketing_click_id
            description: The click ID
            
          - name: marketing_network
            description: The ad network to which the click ID belongs
            
          - name: geo_country
            description: ISO 3166-1 code for the country the visitor is located in
            
          - name: geo_region
            description: ISO-3166-2 code for country region the visitor is in
            
          - name: geo_region_name
            description: Visitor region name
            
          - name: geo_city
            description: City the visitor is in
            
          - name: geo_zipcode
            description: Postcode the visitor is in
            
          - name: geo_latitude
            description: Visitor location latitude
            
          - name: geo_longitude
            description: Visitor location longitude
            
          - name: geo_timezone
            description: Visitor timezone name
            
          - name: ip_address
            description: The IP address of the visitor
            
          - name: ip_isp
            description: Visitor's ISP
            
          - name: ip_organization
            description: Organization associated with the visitor's IP address - defaults to ISP name if none is found
            
          - name: ip_domain
            description: Second level domain name associated with the visitor's IP address
            
          - name: ip_net_speed
            description: Visitor's connection type
            
          - name: browser
            description: The name and version of the visitor's browser
            
          - name: browser_name
            description: The name, or family, of the visitor's browser
            
          - name: browser_major_version
            description: Browser major version
            
          - name: browser_minor_version
            description: Browser minor version
            
          - name: browser_build_version
            description: Browser build version
            
          - name: browser_engine
            description: Browser rendering engine
            
          - name: browser_language
            description: Language the browser is set to
            
          - name: os
            description: The name and version of the visitor's OS
            
          - name: os_name
            description: The name of the visitor's OS
            
          - name: os_major_version
            description: OS major version
            
          - name: os_minor_version
            description: OS minor version
            
          - name: os_build_version
            description: OS build version
            
          - name: os_manufacturer
            description: OS manufacturer
            
          - name: os_timezone
            description: Time zone the OS is set to
            
          - name: device
            description: Device model
            
          - name: device_type
            description: Type of device
            
          - name: device_is_mobile
            description: Is the device mobile?                       
            
          - name: app_id
            description: Application ID