{% macro create_pipe(db_name) %}

    {%- call statement() -%}
        
        create pipe snowplow_pipe as
        copy into {{db_name}}.snowplow.events from (    
            select 
                nullif($1:app_id, '')::string as app_id,
                nullif($1:base_currency, '')::string as base_currency,
                nullif($1:br_colordepth, '')::string as br_colordepth,
                nullif($1:br_cookies, '')::string as br_cookies,
                nullif($1:br_family, '')::string as br_family,
                nullif($1:br_features_director, '')::string as br_features_director,
                nullif($1:br_features_flash, '')::string as br_features_flash,
                nullif($1:br_features_gears, '')::string as br_features_gears,
                nullif($1:br_features_java, '')::string as br_features_java,
                nullif($1:br_features_pdf, '')::string as br_features_pdf,
                nullif($1:br_features_quicktime, '')::string as br_features_quicktime,
                nullif($1:br_features_realplayer, '')::string as br_features_realplayer,
                nullif($1:br_features_silverlight, '')::string as br_features_silverlight,
                nullif($1:br_features_windowsmedia, '')::string as br_features_windowsmedia,
                nullif($1:br_lang, '')::string as br_lang,
                nullif($1:br_name, '')::string as br_name,
                nullif($1:br_renderengine, '')::string as br_renderengine,
                nullif($1:br_type, '')::string as br_type,
                nullif($1:br_version, '')::string as br_version,
                nullif($1:br_viewheight,'')::float as br_viewheight,
                nullif($1:br_viewwidth,'')::float as br_viewwidth,
                nullif($1:collector_tstamp,'')::timestamp_tz as collector_tstamp,
                nullif($1:contexts,'')::object as contexts,
                nullif($1:derived_contexts, '')::string as derived_contexts,
                nullif($1:derived_tstamp,'')::string as derived_tstamp,
                nullif($1:doc_charset,'')::string as doc_charset,
                nullif($1:doc_height,'')::float as doc_height,
                nullif($1:doc_width, '')::float as doc_width,
                nullif($1:domain_sessionid,'')::string as domain_sessionid,
                nullif($1:domain_sessionidx, '')::float as domain_sessionidx,
                nullif($1:domain_userid,'')::string as domain_userid,
                nullif($1:dvce_created_tstamp,'')::string as dvce_created_tstamp,
                nullif($1:dvce_ismobile,'')::boolean as dvce_ismobile,
                nullif($1:dvce_screenheight, '')::float as dvce_screenheight,
                nullif($1:dvce_screenwidth, '')::float as dvce_screenwidth,
                nullif($1:dvce_sent_tstamp,'')::string as dvce_sent_tstamp,
                nullif($1:dvce_type,'')::string as dvce_type,
                nullif($1:etl_tags,'')::string as etl_tags,
                nullif($1:etl_tstamp,'')::string as etl_tstamp,
                nullif($1:event, '')::string as event,
                nullif($1:event_fingerprint, '')::string as event_fingerprint,
                nullif($1:event_format, '')::string as event_format,
                nullif($1:event_id, '')::string as event_id,
                nullif($1:event_name, '')::string as event_name,
                nullif($1:event_vendor, '')::string as event_vendor,
                nullif($1:event_version, '')::string as event_version,
                nullif($1:geo_city, '')::string as geo_city,
                nullif($1:geo_country, '')::string as geo_country,
                nullif($1:geo_latitude, '')::float as geo_latitude,
                nullif($1:geo_longitude, '')::float as geo_longitude,
                nullif($1:geo_region,'')::string as geo_region,
                nullif($1:geo_region_name,'')::string as geo_region_name,
                nullif($1:geo_timezone,'')::string as geo_timezone,
                nullif($1:geo_zipcode, '')::string as geo_zipcode,
                nullif($1:ip_domain, '')::string as ip_domain,
                nullif($1:ip_isp, '')::string as ip_isp,
                nullif($1:ip_netspeed, '')::string as ip_netspeed,
                nullif($1:ip_organization, '')::string as ip_organization,
                nullif($1:mkt_campaign, '')::string as mkt_campaign,
                nullif($1:mkt_clickid, '')::string as mkt_clickid,
                nullif($1:mkt_content, '')::string as mkt_content,
                nullif($1:mkt_medium, '')::string as mkt_medium,
                nullif($1:mkt_network, '')::string as mkt_network,
                nullif($1:mkt_source, '')::string as mkt_source,
                nullif($1:mkt_term, '')::string as mkt_term,
                nullif($1:name_tracker, '')::string as name_tracker,
                nullif($1:network_userid, '')::string as network_userid,
                nullif($1:os_family, '')::string as os_family,
                nullif($1:os_manufacturer, '')::string as os_manufacturer,
                nullif($1:os_name, '')::string as os_name,
                nullif($1:os_timezone, '')::string as os_timezone,
                nullif($1:page_referrer,'')::string as page_referrer,
                nullif($1:page_title,'')::string as page_title,
                nullif($1:page_url,'')::string as page_url,
                nullif($1:page_urlfragment,'')::string as page_urlfragment,
                nullif($1:page_urlhost,'')::string as page_urlhost,
                nullif($1:page_urlpath,'')::string as page_urlpath,
                nullif($1:page_urlport, '')::float as page_urlport,
                nullif($1:page_urlquery,'')::string as page_urlquery,
                nullif($1:page_urlscheme,'')::string as page_urlscheme,
                nullif($1:platform,'')::string as platform,
                nullif($1:pp_xoffset_max, '')::float as pp_xoffset_max,
                nullif($1:pp_xoffset_min, '')::float as pp_xoffset_min,
                nullif($1:pp_yoffset_max, '')::float as pp_yoffset_max,
                nullif($1:pp_yoffset_min, '')::float as pp_yoffset_min,
                nullif($1:refr_domain_userid,'')::string as refr_domain_userid,
                nullif($1:refr_dvce_tstamp,'')::string as refr_dvce_tstamp,
                nullif($1:refr_medium,'')::string as refr_medium,
                nullif($1:refr_source,'')::string as refr_source,
                nullif($1:refr_term,'')::string as refr_term,
                nullif($1:refr_urlfragment,'')::string as refr_urlfragment,
                nullif($1:refr_urlhost,'')::string as refr_urlhost,
                nullif($1:refr_urlpath,'')::string as refr_urlpath,
                nullif($1:refr_urlport, '')::float as refr_urlport,
                nullif($1:refr_urlquery,'')::string as refr_urlquery,
                nullif($1:refr_urlscheme,'')::string as refr_urlscheme,
                nullif($1:se_action,'')::string as se_action,
                nullif($1:se_category,'')::string as se_category,
                nullif($1:se_label,'')::string as se_label,
                nullif($1:se_property,'')::string as se_property,
                nullif($1:se_value,'')::string as se_value,
                nullif($1:ti_category,'')::string as ti_category,
                nullif($1:ti_currency,'')::string as ti_currency,
                nullif($1:ti_name,'')::string as ti_name,
                nullif($1:ti_orderid,'')::string as ti_orderid,
                nullif($1:ti_price,'')::string as ti_price,
                nullif($1:ti_price_base,'')::string as ti_price_base,
                nullif($1:ti_quantity,'')::string as ti_quantity,
                nullif($1:ti_sku,'')::string as ti_sku,
                nullif($1:tr_affiliation,'')::string as tr_affiliation,
                nullif($1:tr_city,'')::string as tr_city,
                nullif($1:tr_country,'')::string as tr_country,
                nullif($1:tr_currency,'')::string as tr_currency,
                nullif($1:tr_orderid,'')::string as tr_orderid,
                nullif($1:tr_shipping,'')::string as tr_shipping,
                nullif($1:tr_shipping_base,'')::string as tr_shipping_base,
                nullif($1:tr_state,'')::string as tr_state,
                nullif($1:tr_tax,'')::string as tr_tax,
                nullif($1:tr_tax_base,'')::string as tr_tax_base,
                nullif($1:tr_total,'')::string as tr_total,
                nullif($1:tr_total_base,'')::string as tr_total_base,
                nullif($1:true_tstamp,'')::string as true_tstamp,
                nullif($1:txn_id,'')::string as txn_id,
                nullif($1:unstruct_event,'')::object as unstruct_event,
                nullif($1:user_fingerprint,'')::string as user_fingerprint,
                nullif($1:user_id, '')::string as user_id,
                nullif($1:user_ipaddress,'')::string as user_ipaddress,
                nullif($1:useragent,'')::string as useragent,
                nullif($1:v_collector,'')::string as v_collector,
                nullif($1:v_etl,'')::string as v_etl,
                nullif($1:v_tracker,'')::string as v_tracker,
                current_timestamp()

            from @{{db_name}}.snowplow.snowplow_s3/
            )
        
    {%- endcall -%}   
    
{% endmacro %}